#include "libtest.h"
#include "hw4.h"

/*
    DO NOT EDIT THIS FILE!
*/

void test_my_strlen() {
    IzTest* t = iztest_new("my_strlen");
    
    iztest_eq(t, "my_strlen(\"abcdef\")", my_strlen("abcdef"), 6);
    iztest_eq(t, "my_strlen(\"\")", my_strlen(""), 0);
    iztest_eq(t, "my_strlen(\"a\\0bcdefgh\")", my_strlen("a\0bcdefgh"), 1);

    iztest_print_results(t);
}

void test_my_strcmp() {
    IzTest* t = iztest_new("my_strcmp");

    iztest_ok(t, "my_strcmp(\"d\", \"\") > 0", my_strcmp("d", "") > 0);
    iztest_ok(t, "my_strcmp(\"zjhzhzhz\", \"gfgfgfg\") > 0", my_strcmp("zjhzhzhz", "gfgfgfg") > 0);
    iztest_ok(t, "my_strcmp(\"\", \"\") == 0", my_strcmp("", "") == 0);
    iztest_ok(t, "my_strcmp(\"ABCDEF\", \"abcdef\") > 0", my_strcmp("ABCDEF", "abcdef") < 0);
    iztest_ok(t, "my_strcmp(\"\\n\", \"\\t\") > 0", my_strcmp("\n", "\t") > 0);
    iztest_ok(t, "my_strcmp(\"\\0\", \"\\0\") == 0", my_strcmp("\0", "\0") == 0);

    iztest_print_results(t);
}

void test_my_atoi() {
    IzTest* t = iztest_new("my_atoi");

    iztest_eq(t, "my_atoi(\"abcdef\")", my_atoi("abcdef"), 0);
    iztest_eq(t, "my_atoi(\"+x\")", my_atoi("+x"), 0);
    iztest_eq(t, "my_atoi(\"-x\")", my_atoi("-x"), 0);
    iztest_eq(t, "my_atoi(\"123456\")", my_atoi("123456"), 123456);
    iztest_eq(t, "my_atoi(\"-9898\")", my_atoi("-9898"), -9898);
    iztest_eq(t, "my_atoi(\"+73\")", my_atoi("+73"), 73);
    iztest_eq(t, "my_atoi(\"+0\")", my_atoi("+0"), 0);
    iztest_eq(t, "my_atoi(\"-0\")", my_atoi("-0"), 0);

    iztest_print_results(t);
}

void test_my_itoa() {
    IzTest* t = iztest_new("my_itoa");

    char buffer[13];
    my_itoa(123456, buffer);
    iztest_eq_str(t, "my_itoa(123456, buffer)", buffer, "123456");

    my_itoa(-123456, buffer);
    iztest_eq_str(t, "my_itoa(-123456, buffer)", buffer, "-123456");

    my_itoa(-1, buffer);
    iztest_eq_str(t, "my_itoa(-1, buffer)", buffer, "-1");

    my_itoa(0, buffer);
    iztest_eq_str(t, "my_itoa(0, buffer)", buffer, "0");

    my_itoa(-2147483647, buffer);
    iztest_eq_str(t, "my_itoa(-2147483647, buffer)", buffer, "-2147483647");

    iztest_print_results(t);
}

void test_fsum() {
    IzTest* t = iztest_new("fsum");

    iztest_eq(t, "fsum()", fsum(), 1123442);

    iztest_print_results(t);
}