#include <time.h>
#include "libtest.h"
#include "questions/q1.h"
#include "questions/q2.h"

/*
    DO NOT EDIT THIS FILE!
*/

void test_self_power() {
    IzTest* t = iztest_new("self_power");
    
    time_t start = clock();
    iztest_eq(t, "self_power()", self_power(), 9110846700);
    time_t end = clock();
    printf("   Execution time: %.2fs", (float) (end - start)/ CLOCKS_PER_SEC);

    iztest_print_results(t);
}

void test_digit_factorials() {
    IzTest* t = iztest_new("digit_factorials");
    
    time_t start = clock();
    iztest_eq(t, "digit_factorials()", digit_factorials(), 40730);
    time_t end = clock();
    printf("   Execution time: %.2fs", (float) (end - start)/ CLOCKS_PER_SEC);
    iztest_print_results(t);
}