#include "libtest.h"
#include "ex4.h"
#include <string.h>

/*
    DO NOT EDIT THIS FILE!
*/

void test_my_strlwr() {
    IzTest* t = iztest_new("my_strlwr");

    char r1[] = "THIS is A teST STriNG.";
    my_strlwr(r1);
    iztest_eq(t, "my_strlwr(\"THIS is A teST STriNG.\")", strcmp(r1, "this is a test string."), 0);

    char r2[] = "123456";
    my_strlwr(r2);
    iztest_eq(t, "my_strlwr(\"123456\")", strcmp(r2, "123456"), 0);

    char r3[] = "";
    my_strlwr(r3);
    iztest_eq(t, "my_strlwr(\"\")", strcmp(r3, ""), 0);

    char r4[] = "d";
    my_strlwr(r4);
    iztest_eq(t, "my_strlwr(\"d\")", strcmp(r4, "d"), 0);

    char r5[] = "aaaaa;sddsdsds";
    my_strlwr(r5);
    iztest_eq(t, "my_strlwr(\"aaaaa;sddsdsds\")", strcmp(r5, "aaaaa;sddsdsds"), 0);

    iztest_print_results(t);
}

void test_my_strupr() {
    IzTest* t = iztest_new("my_strupr");

    char r1[] = "THIS is A teST STriNG.";
    my_strupr(r1);
    iztest_eq(t, "my_strupr(\"THIS is A teST STriNG.\")", strcmp(r1, "THIS IS A TEST STRING."), 0);

    char r2[] = "123456";
    my_strupr(r2);
    iztest_eq(t, "my_strupr(\"123456\")", strcmp(r2, "123456"), 0);

    char r3[] = "";
    my_strupr(r3);
    iztest_eq(t, "my_strupr(\"\")", strcmp(r3, ""), 0);

    char r4[] = "d";
    my_strupr(r4);
    iztest_eq(t, "my_strupr(\"d\")", strcmp(r4, "D"), 0);

    char r5[] = "a\nB";
    my_strupr(r5);
    iztest_eq(t, "my_strupr(\"a\\nB\")", strcmp(r5, "A\nB"), 0);

    iztest_print_results(t);
}

void test_index_of_char() {
    IzTest* t = iztest_new("index_of_char");

    iztest_eq(t, "index_of_char(\"n\")", index_of_char('n'), 0);
    iztest_eq(t, "index_of_char(\"o\")", index_of_char('o'), 1);
    iztest_eq(t, "index_of_char(\"r\")", index_of_char('r'), 12);
    iztest_eq(t, "index_of_char(\"\\n\")", index_of_char('\n'), 38);
    iztest_eq(t, "index_of_char(\".\")", index_of_char('.'), -1);

    iztest_print_results(t);
}